#!/usr/bin/env python3

import sys

lines = sys.stdin.readlines()

for w in lines:
    w = w.strip().split()
    st = []
    nd = []
    for s in w[0]:
        st.append(s)
    for s in w[1]:
        nd.append(s)
    st.sort()
    nd.sort()
    if st == nd:
        print("True")
    else:
        print("False")
